export const enum ModelPath {
    ArchmageFireball                                    = 'Abilities\\Weapons\\FireBallMissile\\FireBallMissile.mdl',
    OrbOfFire                                           = 'war3mapImported\\OrbOfFire.mdx',
    IncinerateMissile                                   = 'Abilities\\Weapons\\LordofFlameMissile\\LordofFlameMissile.mdl',
    IncinerateDeath                                     = 'Abilities\\Spells\\Other\\Incinerate\\FireLordDeathExplode.mdl',
    Firebolt                                            = 'war3mapImported\\Fire_Bolt.mdx',
    RainOfFire                                          = 'war3mapImported\\Rain of Fire III_Missile_01.mdx',
    DeathlessRainOfFire                                 = 'war3mapImported\\Rain of Fire III_DeathlessMissile_01.mdx',
    FireboltRoughMedium                                 = 'war3mapImported\\Firebolt Rough Medium_DL.mdx',
    Rocket                                              = 'war3mapImported\\Rocket.mdx',
    DemolisherMissile                                   = 'Abilities\\Weapons\\DemolisherFireMissile\\DemolisherFireMissile.mdl',
    PhoenixMissile                                      = 'Abilities\\Weapons\\PhoenixMissile\\Phoenix_Missile_mini.mdl',
    Fire                                                = 'Abilities\\Spells\\Items\\AIfb\\AIfbSpecialArt.mdl',
    FlamestrikeMythic06                                 = 'war3mapImported\\Flamestrike I_00.mdx',
    InterceptorShellMissile                             = 'war3mapImported\\Interceptor Shell.mdx',
    Conflagrate                                         = 'war3mapImported\\Conflagrate.mdx',
    Damnation                                           = 'war3mapImported\\Damnation Orange_00.mdx',
    PillarOfFlame                                       = 'war3mapImported\\Pillar of Flame Orange.mdx',
    Ember                                               = 'war3mapImported\\Ember.mdx',
    Immolation                                          = 'Abilities\\Spells\\Other\\ImmolationRed\\ImmolationRedTarget.mdl',
}