gg_snd_BigButtonClick = nil
gg_snd_MouseClick1 = nil
gg_snd_82379__gynation__paper_flip_3 = nil
gg_snd_Open_Book_Sound_Effect = nil
gg_snd_Close_Book_Sound_Effect = nil
function InitGlobals()
end

function InitSounds()
    gg_snd_BigButtonClick = CreateSound("Sound/Interface/BigButtonClick.flac", false, false, false, 0, 0, "DefaultEAXON")
    SetSoundParamsFromLabel(gg_snd_BigButtonClick, "MenuButtonClick")
    SetSoundDuration(gg_snd_BigButtonClick, 390)
    SetSoundVolume(gg_snd_BigButtonClick, 100)
    gg_snd_MouseClick1 = CreateSound("Sound/Interface/MouseClick1.flac", false, false, false, 0, 0, "DefaultEAXON")
    SetSoundParamsFromLabel(gg_snd_MouseClick1, "InterfaceClick")
    SetSoundDuration(gg_snd_MouseClick1, 239)
    SetSoundVolume(gg_snd_MouseClick1, 127)
    gg_snd_82379__gynation__paper_flip_3 = CreateSound("war3mapImported/82379__gynation__paper-flip-3.wav", false, false, false, 0, 0, "DefaultEAXON")
    SetSoundDuration(gg_snd_82379__gynation__paper_flip_3, 500)
    SetSoundChannel(gg_snd_82379__gynation__paper_flip_3, 0)
    SetSoundVolume(gg_snd_82379__gynation__paper_flip_3, 127)
    SetSoundPitch(gg_snd_82379__gynation__paper_flip_3, 1.0)
    gg_snd_Open_Book_Sound_Effect = CreateSound("war3mapImported/Open Book Sound Effect.wav", false, false, false, 0, 0, "DefaultEAXON")
    SetSoundDuration(gg_snd_Open_Book_Sound_Effect, 1126)
    SetSoundChannel(gg_snd_Open_Book_Sound_Effect, 0)
    SetSoundVolume(gg_snd_Open_Book_Sound_Effect, 127)
    SetSoundPitch(gg_snd_Open_Book_Sound_Effect, 1.0)
    gg_snd_Close_Book_Sound_Effect = CreateSound("war3mapImported/Close Book Sound Effect.wav", false, false, false, 0, 0, "DefaultEAXON")
    SetSoundDuration(gg_snd_Close_Book_Sound_Effect, 857)
    SetSoundChannel(gg_snd_Close_Book_Sound_Effect, 0)
    SetSoundVolume(gg_snd_Close_Book_Sound_Effect, 127)
    SetSoundPitch(gg_snd_Close_Book_Sound_Effect, 1.0)
end

function CreateAllItems()
    local itemID
    BlzCreateItemWithSkin(FourCC("gcel"), -168.2, -651.7, FourCC("gcel"))
    BlzCreateItemWithSkin(FourCC("gcel"), -236.1, -673.8, FourCC("gcel"))
    BlzCreateItemWithSkin(FourCC("gcel"), -318.9, -620.0, FourCC("gcel"))
    BlzCreateItemWithSkin(FourCC("gold"), -571.5, -689.1, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -523.4, -769.0, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -465.6, -785.2, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -403.1, -764.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -366.0, -711.7, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -392.3, -642.6, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -435.0, -600.2, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -475.8, -631.3, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -479.2, -674.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -450.1, -698.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -586.8, -586.2, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -464.9, -545.5, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -541.2, -474.3, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -625.7, -547.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -644.7, -642.6, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -620.2, -713.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -580.4, -736.0, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -543.3, -719.2, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -600.0, -644.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -669.6, -709.6, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -582.7, -495.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -559.9, -437.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("gold"), -434.3, -653.9, FourCC("gold"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -84.7, -1072.9, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -19.8, -1144.3, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -7.2, -1184.4, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -84.8, -1106.9, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -152.5, -1071.4, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -190.5, -1083.0, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -217.7, -1109.9, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -286.8, -1096.5, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -322.7, -1052.2, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -283.8, -979.3, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -226.8, -935.3, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -176.1, -973.6, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -263.6, -1057.6, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -137.3, -886.0, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -64.9, -855.1, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -89.4, -831.1, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -228.4, -834.9, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -253.7, -915.1, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -70.0, -942.3, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -41.1, -910.3, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -135.8, -936.5, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -202.5, -791.2, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("lmbr"), -151.6, -999.4, FourCC("lmbr"))
    BlzCreateItemWithSkin(FourCC("ratf"), -191.1, -545.2, FourCC("ratf"))
    BlzCreateItemWithSkin(FourCC("ratf"), -272.2, -561.1, FourCC("ratf"))
end

function CreateUnitsForPlayer0()
    local p = Player(0)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("Hpal"), -298.3, -354.1, 278.270, FourCC("Hpal"))
    SelectHeroSkill(u, FourCC("AHhb"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), 327.3, -624.0, 318.525, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hpea"), 274.8, -717.9, 161.965, FourCC("hpea"))
    u = BlzCreateUnitWithSkin(p, FourCC("hkni"), 154.9, -688.9, 255.407, FourCC("hkni"))
    u = BlzCreateUnitWithSkin(p, FourCC("hrif"), 402.0, -396.2, 296.552, FourCC("hrif"))
    u = BlzCreateUnitWithSkin(p, FourCC("hsor"), 415.6, -648.3, 70.381, FourCC("hsor"))
end

function CreateUnitsForPlayer1()
    local p = Player(1)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("Hamg"), 167.0, -492.4, 5.900, FourCC("Hamg"))
    SelectHeroSkill(u, FourCC("AHbz"))
end

function CreateUnitsForPlayer2()
    local p = Player(2)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("Hmkg"), 127.7, -280.2, 352.940, FourCC("Hmkg"))
    SelectHeroSkill(u, FourCC("AHtb"))
end

function CreateNeutralPassive()
    local p = Player(PLAYER_NEUTRAL_PASSIVE)
    local u
    local unitID
    local t
    local life
    u = BlzCreateUnitWithSkin(p, FourCC("Hjai"), -11.6, -398.7, 184.373, FourCC("Hjai"))
end

function CreatePlayerBuildings()
end

function CreatePlayerUnits()
    CreateUnitsForPlayer0()
    CreateUnitsForPlayer1()
    CreateUnitsForPlayer2()
end

function CreateAllUnits()
    CreatePlayerBuildings()
    CreateNeutralPassive()
    CreatePlayerUnits()
end

function InitCustomPlayerSlots()
    SetPlayerStartLocation(Player(0), 0)
    ForcePlayerStartLocation(Player(0), 0)
    SetPlayerColor(Player(0), ConvertPlayerColor(0))
    SetPlayerRacePreference(Player(0), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(0), false)
    SetPlayerController(Player(0), MAP_CONTROL_USER)
    SetPlayerStartLocation(Player(1), 1)
    ForcePlayerStartLocation(Player(1), 1)
    SetPlayerColor(Player(1), ConvertPlayerColor(1))
    SetPlayerRacePreference(Player(1), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(1), false)
    SetPlayerController(Player(1), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(2), 2)
    ForcePlayerStartLocation(Player(2), 2)
    SetPlayerColor(Player(2), ConvertPlayerColor(2))
    SetPlayerRacePreference(Player(2), RACE_PREF_UNDEAD)
    SetPlayerRaceSelectable(Player(2), false)
    SetPlayerController(Player(2), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(3), 3)
    ForcePlayerStartLocation(Player(3), 3)
    SetPlayerColor(Player(3), ConvertPlayerColor(3))
    SetPlayerRacePreference(Player(3), RACE_PREF_NIGHTELF)
    SetPlayerRaceSelectable(Player(3), false)
    SetPlayerController(Player(3), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(4), 4)
    ForcePlayerStartLocation(Player(4), 4)
    SetPlayerColor(Player(4), ConvertPlayerColor(4))
    SetPlayerRacePreference(Player(4), RACE_PREF_HUMAN)
    SetPlayerRaceSelectable(Player(4), false)
    SetPlayerController(Player(4), MAP_CONTROL_COMPUTER)
    SetPlayerStartLocation(Player(5), 5)
    ForcePlayerStartLocation(Player(5), 5)
    SetPlayerColor(Player(5), ConvertPlayerColor(5))
    SetPlayerRacePreference(Player(5), RACE_PREF_ORC)
    SetPlayerRaceSelectable(Player(5), false)
    SetPlayerController(Player(5), MAP_CONTROL_COMPUTER)
end

function InitCustomTeams()
    SetPlayerTeam(Player(0), 0)
    SetPlayerState(Player(0), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(1), 0)
    SetPlayerState(Player(1), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(2), 0)
    SetPlayerState(Player(2), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(3), 0)
    SetPlayerState(Player(3), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(4), 0)
    SetPlayerState(Player(4), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerTeam(Player(5), 0)
    SetPlayerState(Player(5), PLAYER_STATE_ALLIED_VICTORY, 1)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateAllyBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateAllyBJ(Player(5), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(0), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(1), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(2), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(4), true)
    SetPlayerAllianceStateVisionBJ(Player(3), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(4), Player(5), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(0), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(1), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(2), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(3), true)
    SetPlayerAllianceStateVisionBJ(Player(5), Player(4), true)
end

function InitAllyPriorities()
    SetStartLocPrioCount(1, 3)
    SetStartLocPrio(1, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(1, 1, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(1, 2, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(2, 3)
    SetStartLocPrio(2, 0, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 1, 3, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(2, 2, 4, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(3, 1)
    SetStartLocPrio(3, 0, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(4, 4)
    SetStartLocPrio(4, 0, 0, MAP_LOC_PRIO_HIGH)
    SetStartLocPrio(4, 1, 1, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 2, 2, MAP_LOC_PRIO_LOW)
    SetStartLocPrio(4, 3, 5, MAP_LOC_PRIO_HIGH)
    SetStartLocPrioCount(5, 1)
    SetStartLocPrio(5, 0, 3, MAP_LOC_PRIO_HIGH)
end

function main()
    SetCameraBounds(-3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), -3328.0 + GetCameraMargin(CAMERA_MARGIN_LEFT), 3072.0 - GetCameraMargin(CAMERA_MARGIN_TOP), 3328.0 - GetCameraMargin(CAMERA_MARGIN_RIGHT), -3584.0 + GetCameraMargin(CAMERA_MARGIN_BOTTOM))
    SetDayNightModels("Environment\\DNC\\DNCLordaeron\\DNCLordaeronTerrain\\DNCLordaeronTerrain.mdl", "Environment\\DNC\\DNCLordaeron\\DNCLordaeronUnit\\DNCLordaeronUnit.mdl")
    NewSoundEnvironment("Default")
    SetAmbientDaySound("LordaeronSummerDay")
    SetAmbientNightSound("LordaeronSummerNight")
    SetMapMusic("Music", true, 0)
    InitSounds()
    CreateAllItems()
    CreateAllUnits()
    InitBlizzard()
    InitGlobals()
end

function config()
    SetMapName("TRIGSTR_003")
    SetMapDescription("TRIGSTR_005")
    SetPlayers(6)
    SetTeams(6)
    SetGamePlacement(MAP_PLACEMENT_USE_MAP_SETTINGS)
    DefineStartLocation(0, 128.0, -448.0)
    DefineStartLocation(1, -2496.0, -2368.0)
    DefineStartLocation(2, -2304.0, 2048.0)
    DefineStartLocation(3, 2304.0, 2176.0)
    DefineStartLocation(4, -192.0, -448.0)
    DefineStartLocation(5, 2432.0, 512.0)
    InitCustomPlayerSlots()
    InitCustomTeams()
    InitAllyPriorities()
end

